### ISSUE TITLE
Question about the exmaple

### ISSUE THREAD

**Issue by neur1n** [diku-dk/futhark-cgo20#1]
I'm confused by the initialization of the 24-bit data here:

https://github.com/diku-dk/futhark-sc20/blob/9752c2ac45f50ea4cccab5359aa3e20736e7d46f/library/example.cu#L148

Shouldn't it be something like `res.value = pixel & 0x00ffffff;`?

Thanks.

**Comment by athas** [comment]
It's been a while, but I think that is just to ensure that the final result won't be entirely fully saturated numbers, as that would make it hard to test for correctness.

**Comment by neur1n** [comment]
So it is not computing the actual 24-bit data, but just for benchmarking, is it?

**Comment by athas** [comment]
It is also computing the data.  That's the benchmark.  This program does not do anything useful.

**Comment by neur1n** [comment]
Thanks for your explanation.
